Add the beginnings of proper end-to-end testing for Manticore
lowRISC/manticore pull request #75
Opened 2021-05-04 19:59 UTC by mcy

`manticore-e2e` spawns a TCP child processes to use as a "virtual RoT", which I intend to begin growing a proper conformance suite around. This has three benefits:
1. e2e test for manticore itself are great.
2. We can eventually use this to test Azure's implementation as well.
3. This is intended to (eventually) be an example integration for interested Manticore users.

TODO: Add doc comments to everything.

2021-05-05 01:36 UTC, alistair23 requested changes
Looks good!

A few things.

 1. It's probably worth adding something to the README on how to run this, so that people know to run this as part of development.
 2. This should work well with the AC RoT work :)

PS: I have also tested Manticore with the Azure implementation for basic communication with libMCTP so it does work :)

2021-05-05 01:36 UTC, alistair23 commented on e2e/src/main.rs
> +//#![deny(missing_docs)]
Why add this commented out?

2021-05-05 01:36 UTC, alistair23 commented on e2e/src/pa_rot.rs
> +            max_message_size: 256,
Should this default be the same as the `default_value` above?

2021-05-05 01:36 UTC, alistair23 commented on e2e/src/main.rs
> +//#![deny(missing_docs)]
Ah, just re-read the PR description, ignore this then.

2021-05-11 04:51 UTC, alistair23 approved these changes

2021-07-23 19:19 UTC, cfrantz approved these changes

2021-07-26 18:14 UTC, merged